<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/composer' . '/autoload_real.php';

<<<<<<< HEAD
return ComposerAutoloaderInit61548fa31d5bc76015ea3f2b162f9651::getLoader();
=======
return ComposerAutoloaderInit63f7dd5a8862085c85b6ee1913428f74::getLoader();
>>>>>>> 088104e6c7e52009ea9984ba698e2d110fdde1ab
